name: Sovereign 16KB Forge
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Forge
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Manifest 16KB Shell
        run: |
          sudo apt-get update
          sudo apt-get install -y lld python3-pip zip unzip autoconf libtool pkg-config cmake libffi-dev libssl-dev
          pip install --upgrade buildozer cython
          wget -q https://dl.google.com/android/repository/android-ndk-r27b-linux.zip
          unzip -q android-ndk-r27b-linux.zip
          # Bypassing the local path error by forcing the runner path
          sed -i "s|^android.ndk_path =.*|android.ndk_path = $(pwd)/android-ndk-r27b|" buildozer.spec
          yes | buildozer android debug
      - name: Deposit Asset
        uses: actions/upload-artifact@v4
        with:
          name: Apexyx-Shell
          path: bin/*.apk
